language: r

os:
 - linux

r_check_args: "--no-build-vignettes --no-manual"
r_build_args: "--no-build-vignettes --no-manual"

repos:
  CRAN: https://cran.rstudio.com
  
warnings_are_errors: false

sudo: required

notifications:
 email:
  on_failure: change
